import { Alert, Button, Chip, Grid, IconButton, MenuItem, Snackbar, Stack, TextField, Tooltip, Typography } from '@mui/material';
import { Ban, CheckCheck, Pencil, Plus, Send, ShoppingCart, Trash2, Truck, WalletCards } from 'lucide-react';
import { useState } from 'react';
import { Controller, useFieldArray, useForm, useWatch } from 'react-hook-form';
import { z } from 'zod';
import { ConfirmDialog } from '../../components/common/ConfirmDialog';
import { DataTable } from '../../components/common/DataTable';
import { FormDialog } from '../../components/common/FormDialog';
import { MetricCard } from '../../components/common/MetricCard';
import { PageHeader } from '../../components/common/PageHeader';
import { useAuth } from '../../hooks/useAuth';
import { inventoryService } from '../../services/inventoryService';
import { purchaseOrderService } from '../../services/purchaseOrderService';
import { supplierService } from '../../services/supplierService';
import { formatETB } from '../../utils/currency';

const schema = z.object({ supplierId: z.string().min(1, 'Choose a supplier.'), orderDate: z.string().min(1, 'Order date is required.'), expectedDate: z.string(), notes: z.string(), items: z.array(z.object({ inventoryItemId: z.string().min(1, 'Choose an item.'), quantity: z.number().positive('Quantity must be greater than zero.'), unitCost: z.number().positive('Unit cost must be greater than zero.') })).min(1, 'Add at least one item.') });
const today = () => new Date().toISOString().slice(0, 10);

function PurchaseForm({ order, suppliers, inventory, actor, open, onClose, onSaved }) {
  const activeSuppliers = suppliers.filter((supplier) => supplier.status === 'active' || supplier.id === order?.supplierId);
  const { control, handleSubmit, setError, setValue, formState: { isSubmitting, errors } } = useForm({ values: order ? { supplierId: order.supplierId, orderDate: order.orderDate, expectedDate: order.expectedDate ?? '', notes: order.notes ?? '', items: order.items } : { supplierId: activeSuppliers[0]?.id ?? '', orderDate: today(), expectedDate: '', notes: '', items: [] } });
  const supplierId = useWatch({ control, name: 'supplierId' });
  const { fields, append, remove } = useFieldArray({ control, name: 'items' });
  const availableItems = inventory.filter((item) => !item.supplierId || item.supplierId === supplierId);
  const submit = (values) => { const parsed = schema.safeParse(values); if (!parsed.success) { parsed.error.issues.forEach((issue) => setError(issue.path.join('.'), { message: issue.message })); return; } try { const saved = order ? purchaseOrderService.update(order.id, parsed.data, actor) : purchaseOrderService.create(parsed.data, actor); onSaved(saved, order ? 'Draft purchase order updated.' : 'Draft purchase order created.'); } catch (error) { setError('root', { message: error.message }); } };
  return <FormDialog open={open} title={order ? 'Edit purchase order' : 'New purchase order'} description="Draft a supplier order with inventory quantities and agreed unit costs." submitLabel={order ? 'Save draft' : 'Create draft'} onClose={onClose} onSubmit={handleSubmit(submit)} isSubmitting={isSubmitting} maxWidth="md">
    {errors.root ? <Alert severity="error">{errors.root.message}</Alert> : null}
    <Grid container spacing={2}><Grid size={{ xs: 12, md: 6 }}><Controller name="supplierId" control={control} render={({ field, fieldState }) => <TextField {...field} select label="Supplier" required fullWidth error={Boolean(fieldState.error)} helperText={fieldState.error?.message} onChange={(event) => { field.onChange(event); setValue('items', []); }}>{activeSuppliers.map((supplier) => <MenuItem key={supplier.id} value={supplier.id}>{supplier.name}</MenuItem>)}</TextField>} /></Grid><Grid size={{ xs: 6, md: 3 }}><Controller name="orderDate" control={control} render={({ field, fieldState }) => <TextField {...field} type="date" label="Order date" required fullWidth slotProps={{ inputLabel: { shrink: true } }} error={Boolean(fieldState.error)} helperText={fieldState.error?.message} />} /></Grid><Grid size={{ xs: 6, md: 3 }}><Controller name="expectedDate" control={control} render={({ field }) => <TextField {...field} type="date" label="Expected date" fullWidth slotProps={{ inputLabel: { shrink: true } }} />} /></Grid></Grid>
    <Stack spacing={1.5}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="subtitle2">Purchase items</Typography><Button size="small" startIcon={<Plus size={16} />} disabled={!availableItems.length} onClick={() => append({ inventoryItemId: availableItems[0]?.id ?? '', quantity: 1, unitCost: availableItems[0]?.cost || 1 })}>Add item</Button></Stack>
      {fields.map((entry, index) => <Grid container spacing={1.5} alignItems="center" key={entry.id}><Grid size={{ xs: 12, md: 6 }}><Controller name={`items.${index}.inventoryItemId`} control={control} render={({ field, fieldState }) => <TextField {...field} select label="Inventory item" size="small" required fullWidth error={Boolean(fieldState.error)} helperText={fieldState.error?.message}>{availableItems.map((item) => <MenuItem key={item.id} value={item.id}>{item.name} ({item.unit})</MenuItem>)}</TextField>} /></Grid><Grid size={{ xs: 5, md: 2.5 }}><Controller name={`items.${index}.quantity`} control={control} render={({ field, fieldState }) => <TextField {...field} type="number" label="Quantity" size="small" required fullWidth onChange={(event) => field.onChange(Number(event.target.value))} slotProps={{ htmlInput: { min: 0.001, step: 0.001 } }} error={Boolean(fieldState.error)} helperText={fieldState.error?.message} />} /></Grid><Grid size={{ xs: 5, md: 2.5 }}><Controller name={`items.${index}.unitCost`} control={control} render={({ field, fieldState }) => <TextField {...field} type="number" label="Unit cost" size="small" required fullWidth onChange={(event) => field.onChange(Number(event.target.value))} slotProps={{ htmlInput: { min: 0.01, step: 0.01 } }} error={Boolean(fieldState.error)} helperText={fieldState.error?.message} />} /></Grid><Grid size={{ xs: 2, md: 1 }}><IconButton color="error" onClick={() => remove(index)}><Trash2 size={18} /></IconButton></Grid></Grid>)}
      {errors.items?.message || errors.items?.root?.message ? <Alert severity="error">{errors.items.message ?? errors.items.root.message}</Alert> : null}
    </Stack>
    <Controller name="notes" control={control} render={({ field }) => <TextField {...field} label="Notes" fullWidth multiline minRows={2} />} />
  </FormDialog>;
}

const statusColor = { draft: 'default', submitted: 'info', received: 'success', cancelled: 'error' };

export function PurchaseOrdersPage() {
  const { user } = useAuth(); const [orders, setOrders] = useState(() => purchaseOrderService.list()); const [editing, setEditing] = useState(null); const [formOpen, setFormOpen] = useState(false); const [confirmation, setConfirmation] = useState(null); const [feedback, setFeedback] = useState(null);
  const suppliers = supplierService.list(); const inventory = inventoryService.list(); const supplierMap = new Map(suppliers.map((supplier) => [supplier.id, supplier])); const inventoryMap = new Map(inventory.map((item) => [item.id, item])); const refresh = () => setOrders(purchaseOrderService.list()); const closeForm = () => { setFormOpen(false); setEditing(null); };
  const receivedValue = orders.filter((order) => order.status === 'received').reduce((sum, order) => sum + order.total, 0); const pending = orders.filter((order) => order.status === 'submitted').length;
  const ask = (type, order) => setConfirmation({ type, order });
  const execute = () => { const { type, order } = confirmation; try { if (type === 'submit') purchaseOrderService.submit(order.id, user); if (type === 'receive') purchaseOrderService.receive(order.id, user); if (type === 'cancel') purchaseOrderService.cancel(order.id, user); if (type === 'delete') purchaseOrderService.remove(order.id, user); refresh(); setFeedback({ severity: 'success', message: type === 'receive' ? 'Purchase received and inventory updated.' : `Purchase order ${type === 'delete' ? 'deleted' : `${type}ted`}.` }); } catch (error) { setFeedback({ severity: 'error', message: error.message }); } setConfirmation(null); };
  const columns = [
    { field: 'id', header: 'Order', minWidth: 165, renderCell: (value) => <Typography variant="body2" sx={{ fontWeight: 800 }}>{value.slice(-12)}</Typography> }, { field: 'supplierId', header: 'Supplier', minWidth: 190, getValue: (row) => supplierMap.get(row.supplierId)?.name ?? 'Unknown' }, { field: 'orderDate', header: 'Order date', minWidth: 115 }, { field: 'expectedDate', header: 'Expected', minWidth: 115, renderCell: (value) => value || 'Not set' },
    { field: 'items', header: 'Items', minWidth: 230, sortable: false, renderCell: (value) => value.map((line) => `${inventoryMap.get(line.inventoryItemId)?.name ?? 'Unknown'} × ${line.quantity}`).join(', ') }, { field: 'total', header: 'Total', minWidth: 120, renderCell: (value) => formatETB(value) }, { field: 'status', header: 'Status', minWidth: 105, renderCell: (value) => <Chip size="small" color={statusColor[value]} label={value[0].toUpperCase() + value.slice(1)} /> },
    { field: 'actions', header: 'Actions', minWidth: 175, sortable: false, renderCell: (_value, row) => <Stack direction="row">{row.status === 'draft' ? <><Tooltip title="Edit draft"><IconButton onClick={() => { setEditing(row); setFormOpen(true); }}><Pencil size={17} /></IconButton></Tooltip><Tooltip title="Submit"><IconButton color="primary" onClick={() => ask('submit', row)}><Send size={17} /></IconButton></Tooltip><Tooltip title="Delete"><IconButton color="error" onClick={() => ask('delete', row)}><Trash2 size={17} /></IconButton></Tooltip></> : null}{row.status === 'submitted' ? <><Tooltip title="Receive into stock"><IconButton color="success" onClick={() => ask('receive', row)}><CheckCheck size={17} /></IconButton></Tooltip><Tooltip title="Cancel"><IconButton color="error" onClick={() => ask('cancel', row)}><Ban size={17} /></IconButton></Tooltip></> : null}</Stack> },
  ];
  const confirmationCopy = { submit: ['Submit purchase order?', 'Submitted orders can no longer be edited.', 'Submit'], receive: ['Receive purchase order?', 'This will increase inventory and create permanent stock movements exactly once.', 'Receive'], cancel: ['Cancel purchase order?', 'Cancelled orders cannot be reopened.', 'Cancel order'], delete: ['Delete draft?', 'This draft will be permanently removed.', 'Delete draft'] };
  const copy = confirmation ? confirmationCopy[confirmation.type] : ['', '', ''];
  return <Stack spacing={3}>
    <PageHeader eyebrow="Procurement" title="Purchase orders" description="Draft, submit, receive, and cancel supplier orders with atomic inventory updates." actions={<Button variant="contained" startIcon={<Plus size={18} />} disabled={!suppliers.some((supplier) => supplier.status === 'active')} onClick={() => setFormOpen(true)}>New purchase order</Button>} />
    <Grid container spacing={2}><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Purchase orders" value={orders.length} helper="All lifecycle states" icon={ShoppingCart} /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Awaiting receipt" value={pending} helper="Submitted orders" icon={Truck} tone={pending ? 'warning' : 'success'} /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Received" value={orders.filter((order) => order.status === 'received').length} helper="Stock applied" icon={CheckCheck} tone="success" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Received value" value={formatETB(receivedValue)} helper="Completed procurement" icon={WalletCards} tone="neutral" /></Grid></Grid>
    <DataTable title="Purchase order history" description={`${orders.length} locally persisted purchase orders`} rows={orders} columns={columns} searchPlaceholder="Search purchase orders" emptyTitle="No purchase orders found" initialSort={{ field: 'orderDate', direction: 'desc' }} />
    {formOpen ? <PurchaseForm order={editing} suppliers={suppliers} inventory={inventory} actor={user} open={formOpen} onClose={closeForm} onSaved={(_order, message) => { refresh(); closeForm(); setFeedback({ severity: 'success', message }); }} /> : null}
    <ConfirmDialog open={Boolean(confirmation)} title={copy[0]} description={copy[1]} confirmLabel={copy[2]} destructive={confirmation?.type === 'delete' || confirmation?.type === 'cancel'} onClose={() => setConfirmation(null)} onConfirm={execute} />
    <Snackbar open={Boolean(feedback)} autoHideDuration={4500} onClose={() => setFeedback(null)} anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}><Alert severity={feedback?.severity ?? 'success'} variant="filled" onClose={() => setFeedback(null)}>{feedback?.message}</Alert></Snackbar>
  </Stack>;
}
