import { Alert, Box, Button, Card, CardContent, Container, Grid, Snackbar, Stack, TextField, Typography } from '@mui/material';
import { Clock3, Mail, MapPin, Phone } from 'lucide-react';
import { Controller, useForm } from 'react-hook-form';
import { useState } from 'react';
import { z } from 'zod';
import { contactService } from '../../services/contactService';
import { database } from '../../services/database';

const schema = z.object({ name: z.string().trim().min(2, 'Enter your name.'), email: z.email('Enter a valid email address.'), phone: z.string(), message: z.string().trim().min(10, 'Please provide a little more detail.') });
const defaults = { name: '', email: '', phone: '', message: '' };

export function ConsumerContact() { const settings = database.getSettings(); const [sent, setSent] = useState(false); const { control, handleSubmit, reset, setError } = useForm({ defaultValues: defaults }); const submit = (values) => { const parsed = schema.safeParse(values); if (!parsed.success) { parsed.error.issues.forEach((issue) => setError(issue.path[0], { message: issue.message })); return; } try { contactService.create(parsed.data); reset(); setSent(true); } catch (error) { setError('message', { message: error.message }); } }; const field = (name, label, multiline = false) => <Controller name={name} control={control} render={({ field: input, fieldState }) => <TextField {...input} label={label} fullWidth required={['name', 'email', 'message'].includes(name)} multiline={multiline} minRows={multiline ? 5 : undefined} error={Boolean(fieldState.error)} helperText={fieldState.error?.message} />} />; const details = [[MapPin, 'Visit us', settings.address], [Phone, 'Call us', settings.phone], [Mail, 'Email us', settings.email], [Clock3, 'Opening hours', settings.openingHours]]; return <Container component="main" maxWidth="lg" sx={{ py: { xs: 5, md: 9 } }}><Stack spacing={1} sx={{ mb: 5 }}><Typography color="primary" variant="overline" fontWeight={900}>GET IN TOUCH</Typography><Typography component="h1" variant="h3" fontWeight={900}>We would love to hear from you.</Typography><Typography color="text.secondary">Questions, feedback, or a special request? Send it directly to our restaurant team.</Typography></Stack><Grid container spacing={4}><Grid size={{ xs: 12, md: 5 }}><Stack spacing={2}>{details.map(([Icon, title, value]) => <Card key={title} variant="outlined"><CardContent><Stack direction="row" spacing={2}><Box sx={{ width: 44, height: 44, borderRadius: 2.5, display: 'grid', placeItems: 'center', bgcolor: 'primary.main', color: 'white', flexShrink: 0 }}><Icon size={20} /></Box><Box><Typography fontWeight={900}>{title}</Typography><Typography color="text.secondary">{value}</Typography></Box></Stack></CardContent></Card>)}</Stack></Grid><Grid size={{ xs: 12, md: 7 }}><Card variant="outlined"><CardContent><Stack component="form" spacing={2.5} onSubmit={handleSubmit(submit)} noValidate><Typography variant="h5" fontWeight={900}>Send a message</Typography>{field('name', 'Your name')}{field('email', 'Email address')}{field('phone', 'Phone number (optional)')}{field('message', 'How can we help?', true)}<Button type="submit" variant="contained" size="large">Send message</Button></Stack></CardContent></Card></Grid></Grid><Snackbar open={sent} autoHideDuration={4000} onClose={() => setSent(false)}><Alert severity="success" variant="filled">Your message was saved. Our team will follow up soon.</Alert></Snackbar></Container>; }
