import { Alert, Box, Button, Chip, Container, Grid, Snackbar, Stack, Typography } from '@mui/material';
import { ArrowLeft, Clock3, Plus, ShoppingBag } from 'lucide-react';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useConsumerCart } from '../../hooks/useConsumerCart';
import { menuService } from '../../services/menuService';
import { formatETB } from '../../utils/currency';

export function FoodDetail() { const { id } = useParams(); const item = menuService.getById(id); const categories = new Map(menuService.listCategories().map((entry) => [entry.id, entry.name])); const { addItem, itemCount } = useConsumerCart(); const [added, setAdded] = useState(false); if (!item || !item.available) return <Container maxWidth="md" sx={{ py: 10, textAlign: 'center' }}><Typography variant="h3" fontWeight={900}>Item unavailable</Typography><Typography color="text.secondary" sx={{ my: 2 }}>This menu item is unavailable or no longer exists.</Typography><Button component={Link} to="/menu" startIcon={<ArrowLeft />}>Back to menu</Button></Container>; return <Container component="main" maxWidth="lg" sx={{ py: { xs: 5, md: 9 } }}><Button component={Link} to="/menu" startIcon={<ArrowLeft />} sx={{ mb: 3 }}>Back to menu</Button><Grid container spacing={{ xs: 4, md: 7 }} alignItems="center"><Grid size={{ xs: 12, md: 6 }}><Box component="img" src={item.image} alt={item.name} sx={{ width: '100%', height: { xs: 360, md: 560 }, objectFit: 'cover', bgcolor: 'action.hover', borderRadius: 6 }} /></Grid><Grid size={{ xs: 12, md: 6 }}><Stack spacing={3}><Stack direction="row" spacing={1}><Chip label={categories.get(item.categoryId) ?? item.type} /><Chip icon={<Clock3 size={15} />} label={`${item.prepTimeMinutes} min`} /></Stack><Typography component="h1" variant="h2" fontWeight={900}>{item.name}</Typography><Typography color="primary" variant="h4" fontWeight={900}>{formatETB(item.price)}</Typography><Typography color="text.secondary" fontSize="1.1rem">{item.description}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><Button size="large" variant="contained" startIcon={<Plus />} onClick={() => { addItem(item); setAdded(true); }}>Add to cart</Button><Button size="large" component={Link} to="/cart" variant="outlined" startIcon={<ShoppingBag />}>View cart ({itemCount})</Button></Stack></Stack></Grid></Grid><Snackbar open={added} autoHideDuration={2500} onClose={() => setAdded(false)}><Alert severity="success" variant="filled">{item.name} added to your cart.</Alert></Snackbar></Container>; }
