import { Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { CircleDollarSign, Clock, Eye, ShoppingBag, XCircle } from 'lucide-react';
import { useState } from 'react';
import { DataTable } from '../../components/common/DataTable';
import { MetricCard } from '../../components/common/MetricCard';
import { PageHeader } from '../../components/common/PageHeader';
import { customerService } from '../../services/customerService';
import { orderService } from '../../services/orderService';
import { formatETB } from '../../utils/currency';

const colors = { pending: 'default', preparing: 'warning', ready: 'success', served: 'info', cancelled: 'error' };
function Detail({ order, customer, onClose }) { return <Dialog open={Boolean(order)} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{order?.receiptNumber} · {order?.table}</DialogTitle><DialogContent dividers><Stack spacing={2}><Stack direction="row" gap={1} flexWrap="wrap"><Chip color={colors[order?.status]} label={order?.status} /><Chip color={order?.paymentStatus === 'paid' ? 'success' : 'warning'} label={order?.paymentStatus} />{order?.billRequested ? <Chip color="info" label="Bill requested" /> : null}</Stack><Typography variant="body2">Customer: {customer?.name ?? 'Walk-in'} · Server: {order?.waiterName}</Typography><Stack spacing={1}>{order?.items.map((item) => <Stack key={item.id} direction="row" justifyContent="space-between"><Typography>{item.quantity}× {item.name}{item.notes ? ` — ${item.notes}` : ''}</Typography><Typography>{formatETB(item.price * item.quantity)}</Typography></Stack>)}</Stack><Stack sx={{ borderTop: 1, borderColor: 'divider', pt: 2 }}><Typography>Subtotal: {formatETB(order?.subtotal ?? 0)}</Typography><Typography>Tax: {formatETB(order?.tax ?? 0)}</Typography><Typography>Discount: {formatETB(order?.discount ?? 0)}</Typography><Typography variant="h6" fontWeight={850}>Total: {formatETB(order?.total ?? 0)}</Typography></Stack><Stack spacing={0.5}><Typography fontWeight={800}>Timeline</Typography>{order?.timeline.map((event) => <Typography key={event.id} variant="body2">{new Date(event.timestamp).toLocaleString()} · {event.title}</Typography>)}</Stack></Stack></DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>; }

export function OrderManagementPage() {
  const orders = orderService.list(); const customers = customerService.list(); const customerMap = new Map(customers.map((customer) => [customer.id, customer])); const [status, setStatus] = useState('all'); const [payment, setPayment] = useState('all'); const [selected, setSelected] = useState(null); const filtered = orders.filter((order) => (status === 'all' || order.status === status) && (payment === 'all' || order.paymentStatus === payment)); const paid = orders.filter((order) => order.paymentStatus === 'paid');
  const columns = [{ field: 'receiptNumber', header: 'Order', minWidth: 175, renderCell: (value) => <Typography variant="body2" fontWeight={800}>{value}</Typography> }, { field: 'table', header: 'Service', minWidth: 100 }, { field: 'customerId', header: 'Customer', minWidth: 160, getValue: (row) => customerMap.get(row.customerId)?.name ?? 'Walk-in' }, { field: 'waiterName', header: 'Owner', minWidth: 170 }, { field: 'createdAt', header: 'Created', minWidth: 170, renderCell: (value) => new Date(value).toLocaleString() }, { field: 'total', header: 'Total', minWidth: 120, renderCell: (value) => formatETB(value) }, { field: 'status', header: 'Status', minWidth: 110, renderCell: (value) => <Chip size="small" color={colors[value]} label={value} /> }, { field: 'paymentStatus', header: 'Payment', minWidth: 105, renderCell: (value) => <Chip size="small" color={value === 'paid' ? 'success' : 'warning'} label={value} /> }, { field: 'actions', header: '', minWidth: 70, sortable: false, renderCell: (_value, row) => <Button size="small" startIcon={<Eye size={16} />} onClick={() => setSelected(row)}>View</Button> }];
  return <Stack spacing={3}><PageHeader eyebrow="Operations" title="Orders" description="Search every order, filter operational and payment states, and inspect its complete timeline." /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Orders" value={orders.length} helper="All recorded orders" icon={ShoppingBag} /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Open" value={orders.filter((order) => !['served', 'cancelled'].includes(order.status)).length} helper="Kitchen workflow" icon={Clock} tone="warning" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Paid sales" value={formatETB(paid.reduce((sum, order) => sum + order.total, 0))} helper={`${paid.length} paid orders`} icon={CircleDollarSign} tone="success" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><MetricCard label="Cancelled" value={orders.filter((order) => order.status === 'cancelled').length} helper="Cancelled tickets" icon={XCircle} tone="neutral" /></Grid></Grid><Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5}><TextField select size="small" label="Order status" value={status} onChange={(event) => setStatus(event.target.value)} sx={{ minWidth: 180 }}>{['all', 'pending', 'preparing', 'ready', 'served', 'cancelled'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField select size="small" label="Payment status" value={payment} onChange={(event) => setPayment(event.target.value)} sx={{ minWidth: 180 }}>{['all', 'unpaid', 'paid'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Stack><DataTable title="Order register" description={`${filtered.length} orders match the selected filters`} rows={filtered} columns={columns} searchPlaceholder="Search orders" emptyTitle="No matching orders" initialSort={{ field: 'createdAt', direction: 'desc' }} initialRowsPerPage={10} />{selected ? <Detail order={selected} customer={customerMap.get(selected.customerId)} onClose={() => setSelected(null)} /> : null}</Stack>;
}
