import { Alert, Box, Button, Card, CardContent, Divider, Grid, IconButton, Snackbar, Stack, TextField, Typography } from '@mui/material';
import { Minus, Plus, Send, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { PageHeader } from '../../components/common/PageHeader';
import { useAuth } from '../../hooks/useAuth';
import { useOrders } from '../../hooks/useOrders';
import { useWaiterCart } from '../../hooks/useWaiterCart';
import { database } from '../../services/database';
import { tableService } from '../../services/tableService';
import { formatETB } from '../../utils/currency';

export function WaiterCheckoutPage() {
  const { user } = useAuth(); const cart = useWaiterCart(); const { addOrder } = useOrders(); const navigate = useNavigate(); const [feedback, setFeedback] = useState(null);
  const table = tableService.getById(cart.table); const settings = database.getSettings(); const subtotal = cart.items.reduce((total, item) => total + item.price * item.quantity, 0); const tax = subtotal * (Number(settings.taxRate ?? 0) / 100);
  const submit = () => { try { if (!table || table.status !== 'available') throw new Error('Choose an available table before placing the order.'); const order = addOrder({ tableId: table.id, table: table.name, waiterName: user?.name, items: cart.items }, user); cart.clearCart(); setFeedback({ severity: 'success', message: `${order.receiptNumber} sent to the kitchen.` }); window.setTimeout(() => navigate('/waiter/orders'), 800); } catch (error) { setFeedback({ severity: 'error', message: error.message }); } };
  return <Stack spacing={3}><PageHeader eyebrow="Waiter station" title="Review order" description={`Confirm the ticket for ${table?.name ?? 'the selected table'} before sending it to the kitchen.`} /><Grid container spacing={3} alignItems="flex-start"><Grid size={{ xs: 12, lg: 8 }}><Stack spacing={2}>{cart.items.length ? cart.items.map((item) => <Card key={item.menuItemId} variant="outlined"><CardContent><Grid container spacing={2} alignItems="center"><Grid size={{ xs: 3, sm: 2 }}><Box component="img" src={item.image} alt="" sx={{ width: '100%', aspectRatio: '1', objectFit: 'cover', borderRadius: 2 }} /></Grid><Grid size={{ xs: 9, sm: 5 }}><Typography fontWeight={900}>{item.name}</Typography><Typography color="primary">{formatETB(item.price)}</Typography></Grid><Grid size={{ xs: 9, sm: 3 }}><Stack direction="row" alignItems="center" justifyContent="center"><IconButton onClick={() => cart.decrementItem(item.menuItemId)}><Minus /></IconButton><Typography fontWeight={900}>{item.quantity}</Typography><IconButton onClick={() => cart.incrementItem(item.menuItemId)}><Plus /></IconButton></Stack></Grid><Grid size={{ xs: 3, sm: 2 }} textAlign="right"><IconButton color="error" onClick={() => cart.removeItem(item.menuItemId)}><Trash2 /></IconButton></Grid><Grid size={12}><TextField size="small" fullWidth label="Kitchen notes" value={item.notes} onChange={(event) => cart.updateNotes(item.menuItemId, event.target.value)} /></Grid></Grid></CardContent></Card>) : <Alert severity="info">No items selected. <Button component={Link} to="/waiter/menu">Return to menu</Button></Alert>}</Stack></Grid><Grid size={{ xs: 12, lg: 4 }}><Card variant="outlined"><CardContent><Stack spacing={2}><Typography variant="h5" fontWeight={900}>Order summary</Typography><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Table</Typography><Typography fontWeight={800}>{table?.name ?? 'Not selected'}</Typography></Stack><Divider /><Stack direction="row" justifyContent="space-between"><Typography>Subtotal</Typography><Typography>{formatETB(subtotal)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography>Tax ({settings.taxRate}%)</Typography><Typography>{formatETB(tax)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography variant="h6" fontWeight={900}>Total</Typography><Typography variant="h6" color="primary" fontWeight={900}>{formatETB(subtotal + tax)}</Typography></Stack><Button size="large" variant="contained" startIcon={<Send />} disabled={!cart.items.length || !table || table.status !== 'available'} onClick={submit}>Send to kitchen</Button></Stack></CardContent></Card></Grid></Grid><Snackbar open={Boolean(feedback)} autoHideDuration={3500} onClose={() => setFeedback(null)}><Alert severity={feedback?.severity ?? 'success'} variant="filled">{feedback?.message}</Alert></Snackbar></Stack>;
}
