import { Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, Stack, Tooltip, Typography } from '@mui/material';
import { Eye, Printer, ReceiptText, WalletCards } from 'lucide-react';
import { useState } from 'react';
import { DataTable } from '../../components/common/DataTable';
import { MetricCard } from '../../components/common/MetricCard';
import { PageHeader } from '../../components/common/PageHeader';
import { paymentService } from '../../services/paymentService';
import { formatETB } from '../../utils/currency';

function ReceiptDialog({ receipt, onClose }) {
  return <Dialog open={Boolean(receipt)} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{receipt?.restaurantName} · {receipt?.receiptNumber}</DialogTitle><DialogContent dividers><Stack spacing={2} className="print-receipt"><Stack><Typography variant="body2">Issued: {receipt ? new Date(receipt.issuedAt).toLocaleString() : ''}</Typography><Typography variant="body2">Service: {receipt?.table} · Cashier: {receipt?.cashierName}</Typography></Stack><Stack spacing={1}>{receipt?.items.map((item) => <Stack key={item.id} direction="row" justifyContent="space-between"><Typography>{item.quantity}× {item.name}</Typography><Typography>{formatETB(item.price * item.quantity)}</Typography></Stack>)}</Stack><Stack sx={{ borderTop: 1, borderColor: 'divider', pt: 2 }} spacing={0.5}><Stack direction="row" justifyContent="space-between"><Typography>Subtotal</Typography><Typography>{formatETB(receipt?.subtotal ?? 0)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography>Tax</Typography><Typography>{formatETB(receipt?.tax ?? 0)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography>Discount</Typography><Typography>-{formatETB(receipt?.discount ?? 0)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography variant="h6" fontWeight={850}>Total</Typography><Typography variant="h6" fontWeight={850}>{formatETB(receipt?.total ?? 0)}</Typography></Stack><Typography variant="body2">Paid by {receipt?.paymentMethod}{receipt?.change ? ` · Change ${formatETB(receipt.change)}` : ''}</Typography></Stack></Stack></DialogContent><DialogActions><Button onClick={onClose}>Close</Button><Button variant="contained" startIcon={<Printer size={17} />} onClick={() => window.print()}>Print receipt</Button></DialogActions></Dialog>;
}

export function ReceiptsPage() {
  const receipts = paymentService.listReceipts(); const [selected, setSelected] = useState(null); const today = new Date().toISOString().slice(0, 10); const todayReceipts = receipts.filter((receipt) => receipt.issuedAt.startsWith(today));
  const columns = [{ field: 'receiptNumber', header: 'Receipt', minWidth: 180, renderCell: (value) => <Typography variant="body2" fontWeight={800}>{value}</Typography> }, { field: 'table', header: 'Service', minWidth: 110 }, { field: 'cashierName', header: 'Cashier', minWidth: 170 }, { field: 'paymentMethod', header: 'Method', minWidth: 110 }, { field: 'total', header: 'Total', minWidth: 130, renderCell: (value) => formatETB(value) }, { field: 'issuedAt', header: 'Issued', minWidth: 180, renderCell: (value) => new Date(value).toLocaleString() }, { field: 'actions', header: 'Actions', minWidth: 90, sortable: false, renderCell: (_value, row) => <Tooltip title="View receipt"><IconButton onClick={() => setSelected(row)}><Eye size={18} /></IconButton></Tooltip> }];
  return <Stack spacing={3}><PageHeader eyebrow="Cashier station" title="Receipts" description="Find, inspect, and print immutable receipt snapshots." /><Grid container spacing={2}><Grid size={{ xs: 12, md: 4 }}><MetricCard label="Receipts" value={receipts.length} helper="All completed sales" icon={ReceiptText} /></Grid><Grid size={{ xs: 12, md: 4 }}><MetricCard label="Issued today" value={todayReceipts.length} helper="Today's documents" icon={Printer} tone="success" /></Grid><Grid size={{ xs: 12, md: 4 }}><MetricCard label="Today's value" value={formatETB(todayReceipts.reduce((sum, receipt) => sum + receipt.total, 0))} helper="Receipt totals" icon={WalletCards} tone="neutral" /></Grid></Grid><DataTable title="Receipt lookup" description="Search by receipt number, service point, cashier, or payment method" rows={receipts} columns={columns} searchPlaceholder="Search receipts" emptyTitle="No receipts found" initialSort={{ field: 'issuedAt', direction: 'desc' }} initialRowsPerPage={10} />{selected ? <ReceiptDialog receipt={selected} onClose={() => setSelected(null)} /> : null}</Stack>;
}
