import { Box, CircularProgress, Typography } from '@mui/material';
import { Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { RouteErrorBoundary } from './components/common/RouteErrorBoundary';
import { PermissionRoute } from './routes/PermissionRoute';
import { ProtectedRoute } from './routes/ProtectedRoute';
import { RoleRedirect } from './routes/RoleRedirect';
import { PERMISSION, STAFF_ROUTE_ROLES } from './routes/access';
import { lazyNamed } from './utils/lazyNamed';

const routeModules = import.meta.glob('./{layouts,pages,features}/**/*.{js,jsx}');
const lazy = (path, name) => lazyNamed(routeModules[`${path}.jsx`] ?? routeModules[`${path}.js`], name);
const AdminLayout = lazy('./layouts/AdminLayout', 'AdminLayout'); const AuthLayout = lazy('./layouts/AuthLayout', 'AuthLayout'); const ChefLayout = lazy('./layouts/ChefLayout', 'ChefLayout'); const WaiterLayout = lazy('./layouts/WaiterLayout', 'WaiterLayout'); const CashierLayout = lazy('./layouts/CashierLayout', 'CashierLayout'); const ConsumerLayout = lazy('./layouts/ConsumerLayout', 'ConsumerLayout');
const AdminDashboard = lazy('./pages/admin/Dashboard', 'AdminDashboard'); const ChefDashboard = lazy('./pages/chef/Dashboard', 'ChefDashboard'); const CashierDashboard = lazy('./pages/cashier/Dashboard', 'CashierDashboard'); const WaiterDashboard = lazy('./pages/waiter/Dashboard', 'WaiterDashboard');
const ConsumerHome = lazy('./pages/consumer/Home', 'ConsumerHome'); const ConsumerMenu = lazy('./pages/consumer/Menu', 'ConsumerMenu'); const ConsumerAbout = lazy('./pages/consumer/About', 'ConsumerAbout'); const ConsumerContact = lazy('./pages/consumer/Contact', 'ConsumerContact'); const ConsumerCartPage = lazy('./pages/consumer/Cart', 'ConsumerCartPage'); const FoodDetail = lazy('./pages/consumer/FoodDetail', 'FoodDetail'); const TrackOrderPage = lazy('./pages/consumer/TrackOrder', 'TrackOrderPage'); const QrMenuPage = lazy('./pages/consumer/QrMenu', 'QrMenuPage');
const LoginPage = lazy('./pages/auth/Login', 'LoginPage'); const NotFound = lazy('./pages/NotFound', 'NotFound'); const AccessDenied = lazy('./pages/AccessDenied', 'AccessDenied'); const PlaceholderPage = lazy('./pages/PlaceholderPage', 'PlaceholderPage');
const MenuManagementPage = lazy('./features/menu/MenuManagementPage', 'MenuManagementPage'); const CategoriesPage = lazy('./features/categories/CategoriesPage', 'CategoriesPage'); const OrderManagementPage = lazy('./features/orders/OrderManagementPage', 'OrderManagementPage'); const WaiterOrdersPage = lazy('./features/orders/WaiterOrdersPage', 'WaiterOrdersPage'); const WaiterCheckoutPage = lazy('./features/orders/WaiterCheckoutPage', 'WaiterCheckoutPage'); const WaiterFloorPage = lazy('./features/tables/WaiterFloorPage', 'WaiterFloorPage');
const CashierPosPage = lazy('./features/pos/CashierPosPage', 'CashierPosPage'); const PaymentsPage = lazy('./features/payments/PaymentsPage', 'PaymentsPage'); const ReceiptsPage = lazy('./features/receipts/ReceiptsPage', 'ReceiptsPage'); const InventoryPage = lazy('./features/inventory/InventoryPage', 'InventoryPage'); const TablesPage = lazy('./features/tables/TablesPage', 'TablesPage'); const CustomersPage = lazy('./features/customers/CustomersPage', 'CustomersPage'); const ExpensesPage = lazy('./features/expenses/ExpensesPage', 'ExpensesPage'); const SettingsPage = lazy('./features/settings/SettingsPage', 'SettingsPage'); const PurchaseOrdersPage = lazy('./features/purchasing/PurchaseOrdersPage', 'PurchaseOrdersPage'); const EmployeesPage = lazy('./features/employees/EmployeesPage', 'EmployeesPage'); const RecipesPage = lazy('./features/recipes/RecipesPage', 'RecipesPage'); const ReportsPage = lazy('./features/reports/ReportsPage', 'ReportsPage'); const SuppliersPage = lazy('./features/suppliers/SuppliersPage', 'SuppliersPage'); const RolesPage = lazy('./features/roles/RolesPage', 'RolesPage'); const AuditLogsPage = lazy('./features/audit/AuditLogsPage', 'AuditLogsPage');

function RouteFallback() { return <Box sx={{ minHeight: '100vh', display: 'grid', placeItems: 'center' }}><Box sx={{ textAlign: 'center' }}><CircularProgress aria-label="Loading workspace" /><Typography color="text.secondary" variant="body2" sx={{ mt: 2 }}>Loading workspace…</Typography></Box></Box>; }
const protect = (permission, element) => <PermissionRoute permission={permission}>{element}</PermissionRoute>;

export default function App() { return <BrowserRouter><RouteErrorBoundary><Suspense fallback={<RouteFallback />}><Routes>
  <Route element={<AuthLayout />}><Route path="/login" element={<LoginPage />} /></Route>
  <Route element={<ConsumerLayout />}><Route path="/" element={<ConsumerHome />} /><Route path="/about" element={<ConsumerAbout />} /><Route path="/menu" element={<ConsumerMenu />} /><Route path="/menu/:id" element={<FoodDetail />} /><Route path="/cart" element={<ConsumerCartPage />} /><Route path="/track-order" element={<TrackOrderPage />} /><Route path="/contact" element={<ConsumerContact />} /><Route path="/qr-menu" element={<QrMenuPage />} /></Route>
  <Route path="/access-denied" element={<AccessDenied />} />
  <Route path="/admin" element={<ProtectedRoute allowedRoles={STAFF_ROUTE_ROLES.admin}><AdminLayout /></ProtectedRoute>}><Route index element={<AdminDashboard />} /><Route path="menu" element={protect(PERMISSION.MANAGE_MENU, <MenuManagementPage />)} /><Route path="categories" element={protect(PERMISSION.MANAGE_MENU, <CategoriesPage />)} /><Route path="orders" element={protect(PERMISSION.MANAGE_ORDERS, <OrderManagementPage />)} /><Route path="tables" element={protect(PERMISSION.MANAGE_ORDERS, <TablesPage />)} /><Route path="customers" element={protect(PERMISSION.MANAGE_ORDERS, <CustomersPage />)} /><Route path="expenses" element={protect(PERMISSION.VIEW_REPORTS, <ExpensesPage />)} /><Route path="inventory" element={protect(PERMISSION.MANAGE_INVENTORY, <InventoryPage />)} /><Route path="purchasing" element={protect(PERMISSION.MANAGE_INVENTORY, <PurchaseOrdersPage />)} /><Route path="employees" element={protect(PERMISSION.MANAGE_EMPLOYEES, <EmployeesPage />)} /><Route path="roles" element={protect(PERMISSION.MANAGE_EMPLOYEES, <RolesPage />)} /><Route path="reports" element={protect(PERMISSION.VIEW_REPORTS, <ReportsPage />)} /><Route path="recipes" element={protect(PERMISSION.MANAGE_MENU, <RecipesPage />)} /><Route path="suppliers" element={protect(PERMISSION.MANAGE_INVENTORY, <SuppliersPage />)} /><Route path="audit-logs" element={protect(PERMISSION.MANAGE_EMPLOYEES, <AuditLogsPage />)} /><Route path="settings" element={protect(PERMISSION.MANAGE_SETTINGS, <SettingsPage />)} /></Route>
  <Route path="/cashier" element={<ProtectedRoute allowedRoles={STAFF_ROUTE_ROLES.cashier}><CashierLayout /></ProtectedRoute>}><Route index element={<CashierDashboard />} /><Route path="pos" element={protect(PERMISSION.TAKE_PAYMENT, <CashierPosPage />)} /><Route path="orders" element={protect(PERMISSION.MANAGE_ORDERS, <OrderManagementPage />)} /><Route path="payments" element={protect(PERMISSION.TAKE_PAYMENT, <PaymentsPage />)} /><Route path="receipts" element={protect(PERMISSION.TAKE_PAYMENT, <ReceiptsPage />)} /></Route>
  <Route path="/waiter" element={<ProtectedRoute allowedRoles={STAFF_ROUTE_ROLES.waiter}><WaiterLayout /></ProtectedRoute>}><Route index element={<WaiterFloorPage />} /><Route path="menu" element={protect(PERMISSION.CREATE_ORDER, <WaiterDashboard />)} /><Route path="orders" element={protect(PERMISSION.MANAGE_ORDERS, <WaiterOrdersPage />)} /><Route path="checkout" element={protect(PERMISSION.MANAGE_ORDERS, <WaiterCheckoutPage />)} /></Route>
  <Route path="/chef" element={<ProtectedRoute allowedRoles={STAFF_ROUTE_ROLES.chef}><ChefLayout /></ProtectedRoute>}><Route index element={<ChefDashboard />} /><Route path="queue" element={protect(PERMISSION.PREPARE_ORDERS, <ChefDashboard />)} /><Route path="prep" element={protect(PERMISSION.VIEW_PUBLIC_MENU, <PlaceholderPage title="Inventory alerts" description="Ingredient alerts and preparation planning." />)} /></Route>
  <Route path="/dashboard" element={<RoleRedirect />} /><Route path="*" element={<NotFound />} />
</Routes></Suspense></RouteErrorBoundary></BrowserRouter>; }
