import { Alert, Box, Button, Card, CardContent, Chip, Grid, InputAdornment, Stack, TextField, Typography } from '@mui/material';
import { Clock3, Plus, Search, ShoppingCart } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../../components/common/PageHeader';
import { useOrders } from '../../hooks/useOrders';
import { useWaiterCart } from '../../hooks/useWaiterCart';
import { menuService } from '../../services/menuService';
import { tableService } from '../../services/tableService';
import { formatETB } from '../../utils/currency';

export function WaiterDashboard() {
  const navigate = useNavigate(); const cart = useWaiterCart(); const { orders } = useOrders();
  const categories = menuService.listCategories().filter((entry) => entry.status !== 'inactive'); const menuItems = menuService.list({ available: true }); const selectedTable = tableService.getById(cart.table);
  const [category, setCategory] = useState('all'); const [query, setQuery] = useState('');
  const items = useMemo(() => menuItems.filter((item) => (category === 'all' || item.categoryId === category) && (!query || `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase()))), [category, menuItems, query]);
  const active = orders.filter((order) => order.tableId === cart.table && order.paymentStatus !== 'paid' && order.status !== 'cancelled'); const itemCount = cart.items.reduce((total, item) => total + item.quantity, 0); const subtotal = cart.items.reduce((total, item) => total + item.price * item.quantity, 0);
  return <Stack spacing={3} sx={{ pb: itemCount ? 10 : 0 }}><PageHeader eyebrow="Waiter station" title={`Create order · ${selectedTable?.name ?? 'No table selected'}`} description={selectedTable ? `${selectedTable.section} · ${selectedTable.capacity} seats` : 'Return to the floor and select an available table.'} actions={<TextField size="small" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search menu" slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search size={17} /></InputAdornment> } }} />} />
    {!selectedTable ? <Alert severity="warning">Select a table before building an order.</Alert> : null}<Stack direction="row" spacing={1} sx={{ overflowX: 'auto', pb: 0.5 }}><Chip clickable color={category === 'all' ? 'primary' : 'default'} label="All" onClick={() => setCategory('all')} />{categories.map((entry) => <Chip clickable key={entry.id} color={category === entry.id ? 'primary' : 'default'} label={entry.name} onClick={() => setCategory(entry.id)} />)}</Stack>
    <Grid container spacing={2}><Grid size={{ xs: 12, xl: 9 }}><Grid container spacing={2}>{items.map((item) => <Grid key={item.id} size={{ xs: 12, sm: 6, lg: 4 }}><Card variant="outlined" sx={{ height: '100%', overflow: 'hidden' }}><Box component="img" src={item.image} alt={item.name} sx={{ width: '100%', height: 150, objectFit: 'cover', bgcolor: 'action.hover' }} /><CardContent><Stack spacing={1.5}><Stack direction="row" justifyContent="space-between" gap={2}><Typography fontWeight={900}>{item.name}</Typography><Typography color="primary" fontWeight={900}>{formatETB(item.price)}</Typography></Stack><Typography variant="body2" color="text.secondary">{item.description}</Typography><Stack direction="row" alignItems="center" spacing={0.75}><Clock3 size={15} /><Typography variant="caption">{item.prepTimeMinutes} min</Typography></Stack><Button variant="contained" startIcon={<Plus />} disabled={!selectedTable} onClick={() => cart.addItem(item)}>Add</Button></Stack></CardContent></Card></Grid>)}</Grid></Grid><Grid size={{ xs: 12, xl: 3 }}><Stack spacing={2}><Typography variant="h6" fontWeight={900}>Table activity</Typography>{active.length ? active.map((order) => <Card key={order.id} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={900}>{order.receiptNumber}</Typography><Typography variant="caption" color="text.secondary">{order.items.length} unique items</Typography></Box><Chip size="small" label={order.status} /></Stack></CardContent></Card>) : <Alert severity="info">No active order for this table.</Alert>}</Stack></Grid></Grid>
    {itemCount ? <Box sx={{ position: 'fixed', left: { xs: 0, md: 280 }, right: 0, bottom: 0, zIndex: 10, bgcolor: 'background.paper', borderTop: 1, borderColor: 'divider', p: 2, boxShadow: 8 }}><Stack direction="row" alignItems="center" justifyContent="space-between" maxWidth="xl" mx="auto"><Box><Typography fontWeight={900}>{itemCount} items</Typography><Typography variant="body2" color="text.secondary">{formatETB(subtotal)} before tax</Typography></Box><Button variant="contained" startIcon={<ShoppingCart />} onClick={() => navigate('/waiter/checkout')}>Review order</Button></Stack></Box> : null}
  </Stack>;
}
